# .github/workflows/gh-pages.yml
name: Deploy Hugo site to GitHub Pages

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: 'refs/heads/main' 
          HUGO_ENV: 'refs/heads/main' 
          HUGO_BASEURL: 'https://fairdo.org/' 
        run: hugo --minify

      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: vwebfile.gwdg.de
          username: gwdg.fdo-wordpress
          password: ${{secrets.sftp_pass}}
          port: 2222
          uploads: ./public => ./www/test